-- DROP & CREATE DATABASE
DROP DATABASE IF EXISTS VOTING_SYSTEM;
CREATE DATABASE VOTING_SYSTEM;
USE VOTING_SYSTEM;

-- STUDENT TABLE
CREATE TABLE STUDENT (
  student_id INT PRIMARY KEY AUTO_INCREMENT,
  student_name VARCHAR(255) NOT NULL,
  roll_no INT UNIQUE NOT NULL,
  branch VARCHAR(50) NOT NULL,
  dob DATE DEFAULT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  Pass VARCHAR(255) NOT NULL,
  is_eligible BOOLEAN DEFAULT FALSE,
  prn_id VARCHAR(50) UNIQUE,
  role ENUM('student','party_head','admin') DEFAULT 'student',
  CONSTRAINT fk_student_prn FOREIGN KEY (prn_id)
      REFERENCES ELIGIBLE_STUDENT(prn_id) ON DELETE RESTRICT
);

-- ELIGIBLE STUDENT TABLE
CREATE TABLE ELIGIBLE_STUDENT (
  prn_id VARCHAR(50) PRIMARY KEY,
  email VARCHAR(50) UNIQUE,
  student_name VARCHAR(200)
);

-- ELECTION TABLE
CREATE TABLE ELECTION (
  e_id INT PRIMARY KEY AUTO_INCREMENT,
  e_name VARCHAR(255),
  e_year VARCHAR(20),
  phase ENUM('NOMINATION','WITHDRAWAL','VOTING','RESULT','CLOSED') DEFAULT 'NOMINATION'
);

-- ELECTION POSITION TABLE
CREATE TABLE ELECTION_POSITION (
  ep_id INT PRIMARY KEY AUTO_INCREMENT,
  e_id INT NOT NULL,
  p_name VARCHAR(100),
  status ENUM('nomination','withdrawal','voting','completed','re_election_required') DEFAULT 'nomination',
  FOREIGN KEY (e_id) REFERENCES ELECTION(e_id) ON DELETE CASCADE
);

-- PARTY TABLE
CREATE TABLE PARTY (
  party_id INT PRIMARY KEY AUTO_INCREMENT,
  party_name VARCHAR(255) NOT NULL,
  president_id INT UNIQUE,
  FOREIGN KEY (president_id) REFERENCES STUDENT(student_id) ON DELETE SET NULL
);

-- NOMINATION TABLE
CREATE TABLE NOMINATION (
  nomination_id INT PRIMARY KEY AUTO_INCREMENT,
  election_id INT NOT NULL,
  student_id INT NOT NULL,
  position_id INT NOT NULL,
  party_id INT DEFAULT NULL,
  status ENUM('PENDING','STUDENT_ACCEPTED','STUDENT_REJECTED','ADMIN_APPROVED','ADMIN_REJECTED','WITHDRAWN') DEFAULT 'PENDING',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (election_id, student_id),            -- one position per student per election
  UNIQUE (election_id, position_id, party_id), -- one party candidate per position
  FOREIGN KEY (election_id) REFERENCES ELECTION(e_id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES STUDENT(student_id) ON DELETE CASCADE,
  FOREIGN KEY (position_id) REFERENCES ELECTION_POSITION(ep_id) ON DELETE CASCADE,
  FOREIGN KEY (party_id) REFERENCES PARTY(party_id) ON DELETE SET NULL
);

-- OTP VERIFICATION TABLE
CREATE TABLE OTP_VERIFICATION (
  otp_id INT PRIMARY KEY AUTO_INCREMENT,
  prn_id VARCHAR(50) UNIQUE NOT NULL,
  otp VARCHAR(255) NOT NULL,
  expiresAt DATETIME DEFAULT NULL,
  attempt INT DEFAULT 0,
  blocked_until DATETIME DEFAULT NULL,
  FOREIGN KEY (prn_id) REFERENCES ELIGIBLE_STUDENT(prn_id) ON DELETE CASCADE
);

-- VOTES TABLE (one vote per position per student)
CREATE TABLE VOTE (
  vote_id INT PRIMARY KEY AUTO_INCREMENT,
  ep_id INT NOT NULL,
  student_id INT NOT NULL,
  candidate_nomination_id INT NOT NULL,
  voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ep_id, student_id),
  FOREIGN KEY (ep_id) REFERENCES ELECTION_POSITION(ep_id),
  FOREIGN KEY (student_id) REFERENCES STUDENT(student_id),
  FOREIGN KEY (candidate_nomination_id) REFERENCES NOMINATION(nomination_id)
);

-- MOBILE NUMBERS TABLE (multiple per student allowed)
CREATE TABLE MOBILE (
  mobile_id INT PRIMARY KEY AUTO_INCREMENT,
  student_id INT NOT NULL,
  mobile_num VARCHAR(15) NOT NULL,
  FOREIGN KEY (student_id) REFERENCES STUDENT(student_id) ON DELETE CASCADE
);
